name: pr-lint-action
description: A GitHub Action that verifies your pull request contains a reference to a ticket.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: activity
  color: white
